Resume.delete_all

r1 = Resume.create(:name => 'Ben Clayman', :address => '234 East 5th Street, Apt. E, New York, NY 10003', :phone => '(978) 886-1786', :email => 'benjamin_clayman@alumni.brown.edu',

  :work1 => 'General Assembly', :location1 => 'New York, NY', :role1 => 'Student, Web Development Immersive', :date_range1 => '1/2013 - Present', :work_bullet_1_1 => 'Member of the GA WDI3 Course, a full-time 12-week course covering a variety of programming topics in depth', :work_bullet_1_2 => 'Focused on full-stack web development with Ruby on Rails', :work_bullet_1_3 => 'Other topics: HTML5, CSS3, jQuery and javascript',

  :work2 => 'Barclays Capital', :location2 => 'New York, NY', :role2 => 'Investment Banking Analyst, Corporate Derivatives Origination', :date_range2 => '6/2011 - 3/2012', :work_bullet_2_1 => 'Provide customized strategic advice to power and natural resource companies on how best to mitigate interest rate risk based on future issuance plans, interest in positive carry, and risk appetite', :work_bullet_2_2 => 'Evaluate Barclays principal credit, derivative, and funding exposures based on Expected Exposure, Reverse Expected Exposure, and Expected Mark-to-Market derived from Monte Carlo simulations', :work_bullet_2_3 => 'Gain significant experience modeling interest rate derivatives, including Treasury locks, swaps to fixed, swaps to floating, swaptions, caps, floors, and cross-currency swaps',

  :work3 => 'Barclays Capital', :location3 => 'New York, NY', :role3 => 'Investment Banking Summer Analyst, Restructuring and Finance', :date_range3 => '6/2010 - 8/2010', :work_bullet_3_1 => 'Assisted bankers in turnaround, restructuring, and valuation analysis for distressed clients', :work_bullet_3_2 => 'Only summer analyst in Restructuring to receive full-time offer', :work_bullet_3_3 => 'Baller. Status.',

  :college => 'Brown University', :college_location => 'Providence, RI', :degree_type => 'AB', :degree_subject => 'Philosophy', :college_year => '2011', :gpa => '3.92', :relevant_coursework => 'Multivariable Calculus, Differential Equations, Linear Algebra, Real Analysis, Introduction to Computer Science, Decision Theory, Symbolic Logic', :extra_bullet => 'Mens Varsity Squash Captain: Led team to 12th place finish at 2011 Nationals; Achieved top 75 national individual ranking', :hs => 'Groton School', :hs_location => 'Groton, MA', :hs_year => '2007', :interests => 'Squash, Poker (over $25k lifetime profit), Backgammon (ER: ~9), and Chess')